In [27]:
#Imports
from pymongo import *
from pprint import pprint
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel
import pandas as pd
import spacy
import numpy as np
from nltk.corpus import stopwords
import json
#for many json texts
import glob

#visualization
import pyLDAvis
import pyLDAvis.gensim

In [28]:
#Connection
connection = "mongodb://bouman:80um4N!@ec2-15-188-255-64.eu-west-3.compute.amazonaws.com:27017/"
client = MongoClient(connection)
db = client.get_database ('media_analysis')

In [29]:
#Getting all articles
col = db["articles"]
#IT WORKS LEZGO
fr_news = col.find({'meta.source.language': 'fr'},{"_id":0,"title": 1,"text":1,"date":1}).limit(5000)

In [30]:
#Into the DataFrame
df = pd.DataFrame(data=fr_news)

In [31]:
#checking how many null values
df.isnull().sum()

date     0
text     3
title    0
dtype: int64

In [32]:
#deleting rows with null values
df = df.dropna()

In [33]:
df.to_csv("All_fr_articles.csv")

In [34]:
#1
stopwords = stopwords.words("french")

In [35]:
data = df["text"]
data.head(4)

0    Jamal Khashoggi, critique du régime saoudien a...
1    Coronavirus: plus de 1.200 nouveaux morts aux ...
2    Les concentrations de différents polluants rel...
3    Vous avez aimé la bataille hivernale entre les...
Name: text, dtype: object

In [36]:
# #2 THIS FUNCTION CUTS THE WORD PER
# import pandas as pd
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.cluster import KMeans
# from sklearn.metrics import adjusted_rand_score
# import string
# from nltk.corpus import stopwords
# import glob
# import re

# data_synonyms = [
#     "donnée",
#     "information",
#     "ensemble de données",
#     "jeu de données",
#     "base de données",
#     "informations",
#     "enregistrement",
#     "document",
#     "fait",
#     "renseignement"
# ]
# def remove_stops(text, stops):
#     words = text.split()
#     final = []
#     for word in words:
#         if word not in stops:
#             final.append(word)
#     final = " ".join(final)
#     final = final.translate(str.maketrans("","", string.punctuation))
#     final = "".join([i for i in final if not i.isdigit()])
#     while "  "in final:
#         final = final.replace("  "," ")
#     return (final)
    
# def clean_docs(docs):
#     stops = stopwords.words("french")
#     #stops = stops + data_synonyms
#     final = []
#     for doc in docs:
#         clean_doc = remove_stops(doc,stops)
#         final.append(clean_doc)
#     return (final)

# data = clean_docs(data)
# data[0]

In [37]:
# #3
import spacy
nlp = spacy.load("fr_core_news_sm")

In [38]:
# #4
spacy_docs = list(nlp.pipe(data))
print(spacy_docs[0])

Jamal Khashoggi, critique du régime saoudien après en avoir été proche, a été assassiné et son corps découpé en morceaux le 2 octobre 2018

Les enfants de Jamal Khashoggi, journaliste saoudien assassiné en octobre 2018 dans le consulat d’Arabie saoudite à Istanbul, ont annoncé vendredi qu’ils pardonnaient aux tueurs de leur père.

« Nous, les fils du martyr Jamal Khashoggi, annonçons que nous pardonnons à ceux qui ont tué notre père », a écrit sur Twitter Salah Khashoggi, fils de l’ancien journaliste du Washington Post.

Un meurtre odieux

Jamal Khashoggi, critique du régime saoudien après en avoir été proche, a été assassiné et son corps découpé en morceaux le 2 octobre 2018 dans le consulat d’Arabie saoudite à Istanbul où il s’était rendu pour récupérer un document.


In [39]:
# #5
docs = []
#for doc in data:
for doc in spacy_docs:
    tokens = []
    for token in doc:
        if len(token.orth_) > 3 and not token.is_stop: # prétraitements 1 et 2
            tokens.append( token.lemma_.lower() )  # prétraitements 3 et 4
    docs.append( tokens )
print(docs[0])

['jamal', 'khashoggi', 'critique', 'régime', 'saoudien', 'assassiner', 'corps', 'découper', 'morceau', 'octobre', '2018', 'enfant', 'jamal', 'khashoggi', 'journaliste', 'saoudien', 'assassiner', 'octobre', '2018', 'consulat', 'arabie', 'saoudite', 'istanbul', 'annoncer', 'vendredi', 'pardonner', 'tueur', 'père', 'fils', 'martyr', 'jamal', 'khashoggi', 'annonçon', 'pardonner', 'père', 'écrire', 'twitter', 'salah', 'khashoggi', 'fils', 'ancien', 'journaliste', 'washington', 'post', 'meurtre', 'odieux', 'jamal', 'khashoggi', 'critique', 'régime', 'saoudien', 'assassiner', 'corps', 'découper', 'morceau', 'octobre', '2018', 'consulat', 'arabie', 'saoudite', 'istanbul', 'rendre', 'récupérer', 'document']


In [40]:
#6
#Bigram trigrams
bigram = gensim.models.Phrases(docs, min_count=5, threshold=100) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[docs], threshold=100)  

# Faster way to get a sentence clubbed as a trigram/bigram
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)

# See trigram example
print(trigram_mod[bigram_mod[docs[0]]])
#7
# Define functions for stopwords, bigrams, trigrams and lemmatization
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) if word not in stopwords] for doc in texts]

def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]

def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]

def lemmatization(texts, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV']):
    """https://spacy.io/api/annotation"""
    texts_out = []
    for sent in texts:
        doc = nlp(" ".join(sent)) 
        texts_out.append([token.lemma_ for token in doc if token.pos_ in allowed_postags])
    return texts_out

#8
# Remove Stop Words
#data_words_nostops = remove_stopwords(docs)

# Form Bigrams
data_words_bigrams = make_bigrams(docs)

# Initialize spacy 'en' model, keeping only tagger component (for efficiency)
# python3 -m spacy download en
nlp = spacy.load('fr_core_news_sm', disable=['parser', 'ner'])

# Do lemmatization keeping only noun, adj, vb, adv
data_lemmatized = lemmatization(data_words_bigrams, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV'])

print(data_lemmatized[:3])
#Seems like it cuts weirdly, it has "pèr" and "père"

['jamal_khashoggi', 'critique_régime_saoudien', 'assassiner_corps_découper_morceau', 'octobre', '2018', 'enfant', 'jamal_khashoggi', 'journaliste', 'saoudien_assassiner', 'octobre_2018_consulat', 'arabie_saoudite', 'istanbul', 'annoncer', 'vendredi', 'pardonner', 'tueur', 'père', 'fils', 'martyr', 'jamal_khashoggi', 'annonçon', 'pardonner', 'père', 'écrire', 'twitter', 'salah_khashoggi', 'fils', 'ancien', 'journaliste_washington_post', 'meurtre', 'odieux', 'jamal_khashoggi', 'critique_régime_saoudien', 'assassiner_corps_découper_morceau', 'octobre_2018_consulat', 'arabie_saoudite', 'istanbul', 'rendre', 'récupérer', 'document']
[['jamal_khashoggi', 'critique', 'régime_saoudien', 'assassiner_corps', 'découper_morceau', 'octobre', 'enfant', 'journaliste', 'saoudien_assassiner', 'octobre', 'istanbul', 'annoncer', 'vendredi', 'pardonner', 'tueur', 'pèr', 'fil', 'martyr', 'annonçon', 'pardonner', 'père', 'écrir', 'twitter', 'salah_khashoggi', 'fils', 'ancien', 'journaliste', 'washington_pos

In [41]:
#useless TF IDF
# from sklearn.feature_extraction.text import TfidfVectorizer

# # Assuming data_lemmatized is a list of lists, e.g., [['word1', 'word2'], ['word3', 'word4']]
# # Flatten the list of lists into a list of strings
# data_lemmatized_flat = [' '.join(doc) for doc in data_lemmatized]

# # Create a TF-IDF vectorizer
# vectorizer = TfidfVectorizer()

# # Fit and transform the flattened data
# tfidf_matrix = vectorizer.fit_transform(data_lemmatized_flat)

# # Get the feature names (words)
# feature_names = vectorizer.get_feature_names_out()

# # Convert the TF-IDF matrix to an array for better readability
# tfidf_array = tfidf_matrix.toarray()

# # Print the feature names and TF-IDF matrix
# print("Feature Names (Words):", feature_names)
# print("TF-IDF Matrix:")
# print(tfidf_array)


Feature Names (Words): ['00' '000' '000_supporter' ... 'œuvre' 'œuvrer' 'œuvré']
TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [63]:
#9
# Create Dictionary
#replace docs by data_lemmatized
#id2word = corpora.Dictionary(docs)

id2word = corpora.Dictionary(data_lemmatized)
print(f"Before filter : {len(id2word)}")
#id2word.filter_extremes(no_below=5,no_above=0.05)
print(f"After filter : {len(id2word)}")
# Create Corpus
#replace docs by data_lemmatized
#texts = docs
texts = data_lemmatized

# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in texts]

# View
print(corpus[:1])

Before filter : 35635
After filter : 35635
[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 2), (6, 1), (7, 2), (8, 1), (9, 1), (10, 1), (11, 2), (12, 1), (13, 2), (14, 1), (15, 1), (16, 3), (17, 1), (18, 2), (19, 1), (20, 1), (21, 1), (22, 1), (23, 2), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1)]]


In [64]:
id2word[5]

'critique'

In [65]:
#10
# Build LDA model
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=10, 
                                           random_state=100,
                                           update_every=1,
                                           chunksize=300,
                                           passes=10,
                                           alpha='auto',
                                           per_word_topics=True)

In [66]:
#11
# Compute Perplexity
print('\nPerplexity: ', lda_model.log_perplexity(corpus))  # a measure of how good the model is. lower the better.

# Compute Coherence Score
#replace docs by data_lemmatized
coherence_model_lda = CoherenceModel(model=lda_model, texts=texts, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nCoherence Score: ', coherence_lda)
#Best coherence = 0.49 (10 topics, 500 chunk_size)
#nice graph coh 0.45 (13 200)
#0.48 (13 400)
#0.49 (12 400)


Perplexity:  -9.275452134222075

Coherence Score:  0.48272388295811963


In [69]:
# Visualize the topics
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
vis
pyLDAvis.save_html(vis,"models_maciej/model2_vis.html")

In [70]:
# Save the model using joblib
import joblib
model_filename = 'models_maciej/lda_model_2_check_description.joblib'
joblib.dump(lda_model, model_filename)

['models_maciej/lda_model_2_check_description.joblib']